### ISSUE TITLE
Can we make this program more efficient (Enhancement)

### ISSUE THREAD

**Issue by CodeWizarz** [pixelomer/bin2video#1]
# Memory Improvement
I tried to compile some medium sized zip and rar files it works fine with that but if we are to encode a large file about 1gb its very slow maybe ram consumption can be set so the process should be fast as for now encoding at kb's speed would take a whole day for a large file. I have seen in dvorakDwarf repo that if we compile large files the program gets interrupted due to poor ram usage. Can u tell us if this has any loopholes like (isg)

**Comment by pixelomer** [comment]
The program is optimized to use the least amount of memory possible so giving the program more RAM will not change anything. Even if it did, the process will not get any faster since the bottleneck is FFmpeg and not bin2video. It might be possible to speed FFmpeg up by using different video encodings and pixel formats but I assume speeding it up this way will also increase the risk of corruption.

**Comment by CodeWizarz** [comment]
> The program is optimized to use the least amount of memory possible so giving the program more RAM will not change anything. Even if it did, the process will not get any faster since the bottleneck is FFmpeg and not bin2video. It might be possible to speed FFmpeg up by using different video encodings and pixel formats but I assume speeding it up this way will also increase the risk of corruption.

why not try .mkv video format as it has least corruption rate compared to those of .avi and .mp4 and as for ffmpeg i dont know any other alternatives yeah and if itself can be tuned up then its quite awesome.

**Comment by pixelomer** [comment]
The video container format has nothing to do with the corruption rate or the resulting video data.

**Comment by pixelomer** [comment]
As of commit 4f65f6f you can specify the option `-F '-c:v png'` to tell FFmpeg to use the PNG encoder rather than libx264 which is the default. This should make the process much faster (around 4 times faster for my setup) but the video player compatibility for the output will be much lower.
